users_index:
    path:     /
    defaults: { _controller: "UserBundle:User:index" }
    methods:  GET

admin_user_add:
    path:     /admin/membre/ajouter
    defaults: { _controller: UserBundle:User:add }
    methods:  [GET, POST]