admin:
    path:     /admin
    defaults: { _controller: PlatformBundle:Platform:userProfil }

conditions:
    path:     /conditions
    defaults: { _controller: PlatformBundle:Platform:conditions }

admin_users:
    path:     /admin/users
    defaults: { _controller: UserBundle:User:index }


user_observations:
    path:     /profil/observations
    defaults: { _controller: PlatformBundle:Platform:userObservations }

observation_view:
    path:     /profil/observation/{id}
    defaults: { _controller: ObservationBundle:Observation:view }
    methods:  [GET, POST]

user_edit:
    path:     /profil/modifier
    defaults: { _controller: PlatformBundle:Platform:profilEdit }

user_profil:
    path:     /profil
    defaults: { _controller: PlatformBundle:Platform:userProfil }

user_pending:
    path:     /profil/pending
    defaults: { _controller: PlatformBundle:Platform:userPending }

admin_observation_edit:
    path:     /admin/observation/{id}/modifier
    defaults: { _controller: ObservationBundle:Observation:edit }
    methods:  [GET, POST]
