admin:
    path:     /admin
    defaults: { _controller: UserBundle:User:index }


user_observations:
    path:     /profil/observations
    defaults: { _controller: PlatformBundle:Platform:userObservations }

observation_view:
    path:     /profil/observation/{id}
    defaults: { _controller: PlatformBundle:Platform:ObservationView }
    methods:  [GET, POST]

user_edit:
    path:     /profil/modifier
    defaults: { _controller: PlatformBundle:Platform:userEdit }

user_profil:
    path:     /profil
    defaults: { _controller: PlatformBundle:Platform:userProfil }

admin_observation_edit:
    path:     /admin/observation/{id}/modifier
    defaults: { _controller: ObservationBundle:Observation:edit }
    methods:  [GET, POST]

admin_observation_delete:
    path:     /admin/observation/{id}/supprimer
    defaults: { _controller: ObservationBundle:Observation:delete }
    methods:  [GET, POST]
