platform:
    resource: "@PlatformBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

observation:
    resource: "@ObservationBundle/Resources/config/routing.yml"
    prefix:   /