# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
            UserBundle\Entity\User: bcrypt

    role_hierarchy:
            ROLE_MEMBER:      ROLE_PAR
            ROLE_ADMIN:       ROLE_PRO
            ROLE_SUPER_ADMIN: ROLE_ADMIN


    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity: { class: UserBundle:User, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous:  true
            provider:   main
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            logout:
                path: /logout

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }