homepage:
    path:     /
    defaults: { _controller: "ObservationBundle:Oiseau:index" }

oiseau_view:
    path:     /oiseau/{slug}
    defaults: { _controller: "ObservationBundle:Oiseau:view" }
    methods:  [GET, POST]

observation_add:
    path:     /oiseau/{slug}/add
    defaults: { _controller: "ObservationBundle:Oiseau:add" }
    methods:  [GET, POST]
