homepage:
    path:     /
    defaults: { _controller: "ObservationBundle:Oiseau:index" }

oiseau_view:
    path:     /oiseau/{slug}
    defaults: { _controller: "ObservationBundle:Oiseau:view" }
    methods:  [GET, POST]

observation_add:
    path:     /oiseau/{slug}/add
    defaults: { _controller: "ObservationBundle:Oiseau:add" }
    methods:  [GET, POST]

security_login:
    path:     /login
    defaults: { _controller: UserBundle:Security:login }

security_logout:
    path:     /logout
    defaults: { _controller: UserBundle:Security:logout }

user_register:
    path:     /register/
    defaults: { _controller: UserBundle:User:register }
